# Apply to all files without commiting:
#   pre-commit run --all-files
# Update this file:
#   pre-commit autoupdate
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-ast
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: mixed-line-ending
      - id: debug-statements
      - id: check-case-conflict
  - repo: https://github.com/psf/black
    rev: 21.7b0
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.23.0
    hooks:
      - id: pyupgrade
        args: [--py38-plus]
  - repo: https://github.com/PyCQA/flake8.git
    rev: 3.9.2
    hooks:
      - id: flake8
        exclude: ^(Starter|Java|data|C)
        additional_dependencies:
          ["flake8-black>=0.1.1", "flake8-bugbear>=21.4.0"]
        language_version: python3
        args:
          [
            "--max-line-length=82",
            "--max-doc-length=84",
            "--show-source",
            "--statistics",
            "--max-complexity=12",
            "--extend-ignore=E203",
            "--select=C,E,F,W,B,B903",
          ]
